// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: pkg/protobuf/get_user.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserPayload) Reset() {
	*x = UserPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_get_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPayload) ProtoMessage() {}

func (x *UserPayload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_get_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPayload.ProtoReflect.Descriptor instead.
func (*UserPayload) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_get_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Status   string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UserCode string `protobuf:"bytes,3,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
}

func (x *UserDataResp) Reset() {
	*x = UserDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protobuf_get_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResp) ProtoMessage() {}

func (x *UserDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_get_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataResp.ProtoReflect.Descriptor instead.
func (*UserDataResp) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_get_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserDataResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDataResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserDataResp) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

var File_pkg_protobuf_get_user_proto protoreflect.FileDescriptor

var file_pkg_protobuf_get_user_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67,
	0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67,
	0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x32, 0x4c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15,
	0x2e, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_protobuf_get_user_proto_rawDescOnce sync.Once
	file_pkg_protobuf_get_user_proto_rawDescData = file_pkg_protobuf_get_user_proto_rawDesc
)

func file_pkg_protobuf_get_user_proto_rawDescGZIP() []byte {
	file_pkg_protobuf_get_user_proto_rawDescOnce.Do(func() {
		file_pkg_protobuf_get_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protobuf_get_user_proto_rawDescData)
	})
	return file_pkg_protobuf_get_user_proto_rawDescData
}

var file_pkg_protobuf_get_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protobuf_get_user_proto_goTypes = []interface{}{
	(*UserPayload)(nil),  // 0: get_user.UserPayload
	(*UserDataResp)(nil), // 1: get_user.UserDataResp
}
var file_pkg_protobuf_get_user_proto_depIdxs = []int32{
	0, // 0: get_user.GetUserService.GetUser:input_type -> get_user.UserPayload
	1, // 1: get_user.GetUserService.GetUser:output_type -> get_user.UserDataResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protobuf_get_user_proto_init() }
func file_pkg_protobuf_get_user_proto_init() {
	if File_pkg_protobuf_get_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_protobuf_get_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protobuf_get_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protobuf_get_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protobuf_get_user_proto_goTypes,
		DependencyIndexes: file_pkg_protobuf_get_user_proto_depIdxs,
		MessageInfos:      file_pkg_protobuf_get_user_proto_msgTypes,
	}.Build()
	File_pkg_protobuf_get_user_proto = out.File
	file_pkg_protobuf_get_user_proto_rawDesc = nil
	file_pkg_protobuf_get_user_proto_goTypes = nil
	file_pkg_protobuf_get_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetUserServiceClient is the client API for GetUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetUserServiceClient interface {
	GetUser(ctx context.Context, in *UserPayload, opts ...grpc.CallOption) (*UserDataResp, error)
}

type getUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetUserServiceClient(cc grpc.ClientConnInterface) GetUserServiceClient {
	return &getUserServiceClient{cc}
}

func (c *getUserServiceClient) GetUser(ctx context.Context, in *UserPayload, opts ...grpc.CallOption) (*UserDataResp, error) {
	out := new(UserDataResp)
	err := c.cc.Invoke(ctx, "/get_user.GetUserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserServiceServer is the server API for GetUserService service.
type GetUserServiceServer interface {
	GetUser(context.Context, *UserPayload) (*UserDataResp, error)
}

// UnimplementedGetUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGetUserServiceServer struct {
}

func (*UnimplementedGetUserServiceServer) GetUser(context.Context, *UserPayload) (*UserDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterGetUserServiceServer(s *grpc.Server, srv GetUserServiceServer) {
	s.RegisterService(&_GetUserService_serviceDesc, srv)
}

func _GetUserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/get_user.GetUserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserServiceServer).GetUser(ctx, req.(*UserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "get_user.GetUserService",
	HandlerType: (*GetUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _GetUserService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protobuf/get_user.proto",
}
