version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
    volumes:
      - .:/app
    depends_on:
      -   memsql
    command: sh -c './run.sh hot-serve'
    networks:
      - bitwyre
    ports:
      - "3000:3000"

  memsql:
    image: memsql/cluster-in-a-box:latest
    hostname: memsql
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      LICENSE_KEY: ${SINGLESTORE_LICENSE_KEY}
      START_AFTER_INIT: 'Y'
      ROOT_PASSWORD: 'root'
    restart: on-failure
    networks:
      - bitwyre
    volumes:
      - memsql-data:/var/lib/memsql

  jaeger:
    image: jaegertracing/all-in-one:1.7
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - bitwyre

volumes:
  memsql-data:

networks:
  bitwyre:
    driver: bridge
