version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    command: sh -c './run.sh hot-serve'
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sample_db
    ports:
      - "5432:5432"

  memsql:
    image: memsql/cluster-in-a-box
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      LICENSE_KEY: ${SINGLESTORE_LICENSE_KEY}
      START_AFTER_INIT: 'Y'
      ROOT_PASSWORD: 'root'
    restart: on-failure
    volumes:
      - ${PWD}/.memsql:/var/lib/mysql