name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build single job
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-url: https://viper.bitwyre.id
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-job: "order_service_go/main"
#          jenkins-job-params: "{'any_param': 'any_value'}"
#          jenkins-wait-job: "no-wait"
          jenkins-ssl-verify: "true"