name: trigger jenkins job
on: [push]

env:
  SERVICE_NAME: "order_service_go"

jobs:
  build:
    name: trigger-jenkins
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v31
        with:
          files: |
            pkg/**
      - name: Build single job
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: Mondtic/build-jenkins-job@master
        with:
          jenkins-url: https://viper.bitwyre.id
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-job: ${{ env.SERVICE_NAME }}/${{ github.ref_name }}
          jenkins-wait-job: "wait"
          jenkins-ssl-verify: "true"